apiVersion: v1
kind: Service
metadata:
        name: wordpress
	labels:
		app:wordpress
spec:
        ports:
                - port: 31000
                  nodePort: 31000
                  protocol: TCP
        selector:
		  app: wordpress
		  tier: frontend
        type: NodePort

